from __future__ import annotations

from textwrap import shorten


FILE_SUMMARY: dict[str, str] = {
    "_pycache_/": "Python bytecode cache directory generated by recent runs.",
    "venv/": "Local virtual environment with project Python dependencies.",
    "actions.npy": "NumPy array dataset, likely recorded actions for training/replay.",
    "auto_walk.py": "Scripted autonomous walking controller in PyBullet.",
    "auto_walk1.py": "Variant autonomous walking script with foot-contact helper logic.",
    "balance_model.zip": "Saved RL model/checkpoint for balance-related experiments.",
    "base.py": "Minimal baseline script to load robot and run simple simulation setup.",
    "dog.py": "Early quadruped control script for direct joint movement tests.",
    "dog1.py": "Alternative dog control prototype with modified joint commands.",
    "dogslider.py": "Interactive slider-based GUI control for robot joints.",
    "forward.py": "Forward-motion control trial using predefined gait/joint updates.",
    "ik.py": "Inverse-kinematics experiment for target leg positioning.",
    "ik_walk.py": "IK-based walking loop with small RL-style correction term.",
    "laikago_imitation_v1.zip": "Saved policy/model artifact for Laikago imitation run.",
    "RL_stand.py": "Gym-style Laikago standing environment with train/test flow.",
    "RL_troit.py": "Trot gait loop with observation collection and runtime dashboard output.",
    "Rl_troit_walk.py": "Gym-style RL training and testing pipeline for trot walking.",
    "rl.py": "Dog standing RL environment and full train/test execution script.",
    "rl_with_ik.py": "RL environment that combines policy learning with IK control behavior.",
    "sine_waves_base.py": "Base sinusoidal gait generator for periodic leg motion.",
    "slider.py": "Simple UI-slider script for manual joint tuning in simulation.",
    "stability.py": "Robot stability balancing test with posture control heuristics.",
    "stage1_rl.py": "Stage-1 balance RL environment (DogBalanceEnv) and training.",
    "stage1_test.py": "Evaluation script for the stage-1 trained policy/model.",
    "stage1_walk_rl.py": "Stage-1 walking-focused reinforcement learning experiment.",
    "stage2_rl.py": "Stage-2 RL script building on earlier stage training results.",
    "stage2_rl_1.py": "Alternate stage-2 RL variant with adjusted training behavior.",
    "standing.py": "Simple standing posture script without full RL training loop.",
    "test2.py": "Small PyBullet test script (quick simulation sanity check).",
    "test3.py": "Additional ad-hoc simulation test script for robot behavior.",
    "test4.py": "Short test script variant for quick environment checks.",
    "test5.py": "Another short test variant for basic simulation validation.",
    "test_RL.py": "Loads trained RL model and runs inference/testing episodes.",
    "test_rl_troit.py": "Gym-based test environment for validating trained trot policy.",
    "test_stand.py": "Stand-task model load and test run for LaikagoEnv.",
    "walking_sine_waves.py": "Walking controller using sinusoidal trajectories.",
    "walking_sine_waves1.py": "Extended sine-wave walking variant with richer control logic.",
}


def render_summary() -> str:
    """Return a pretty, stable summary block."""
    lines = ["Robo/AI file summary", "=" * 22]
    for name in sorted(FILE_SUMMARY):
        desc = shorten(FILE_SUMMARY[name], width=110, placeholder="...")
        lines.append(f"- {name}: {desc}")
    return "\n".join(lines)


if __name__ == "__main__":
    print(render_summary())

